<?php

namespace FacebookBundle\Repository;

/**
 * AmieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmieRepository extends \Doctrine\ORM\EntityRepository
{
}
